[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 7879a040801
addons_path = d:\Desktop\Odoo\addons,d:\Desktop\Odoo\custom_addons
data_dir = d:\Desktop\Odoo\.odoo_data
default_productivity_apps = True
