{
    "name": "Logistics Base",
    "version": "19.0.1.1.0",
    "summary": "Logistics master data extensions",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "contacts",
        "base_geolocalize",
        "hr",
        "product",
        "stock",
        "fleet",
    ],
    "data": [
        "security/logistics_base_security.xml",
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/hr_employee_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/stock_warehouse_views.xml",
        "views/logistics_base_profile_views.xml",
    ],
    "installable": True,
    "application": False,
}
