{
    "name": "ERP Base",
    "version": "19.0.1.0.0",
    "summary": "ERP / WMS / TMS / BI unified security and menu framework",
    "author": "Tianshu Tech",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "product",
        "sale",
        "sale_stock",
        "purchase",
        "purchase_stock",
        "account",
        "stock",
        "stock_picking_batch",
        "fleet",
        "hr",
        "logistics_base",
        "logistics_dispatch",
        "logistics_trace_core",
        "logistics_trace_evidence",
        "logistics_trace_exception",
        "logistics_web",
    ],
    "data": [
        "security/erp_base_security.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "application": True,
}
