{
    "name": "ERP Base",
    "version": "19.0.1.0.0",
    "summary": "ERP / WMS / TMS / BI unified security and menu framework",
    "author": "Tianshu Tech",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "product",
        "sale",
        "sale_stock",
        "purchase",
        "purchase_stock",
        "account",
        "stock",
        "fleet",
        "hr",
    ],
    "data": [
        "security/erp_base_security.xml",
        "security/ir.model.access.csv",
        "security/erp_acl_cleanup.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/erp_import_template_views.xml",
        "views/product_price_adjustment_views.xml",
        "views/erp_order_import_views.xml",
        "views/erp_delivery_plan_views.xml",
        "views/erp_finance_views.xml",
        "views/sale_purchase_ext_views.xml",
        "views/erp_dashboard_template.xml",
    ],
    "installable": True,
    "application": True,
}
