from . import base_import_mapping
from . import logistics_dashboard_service
from . import logistics_driver_service
from . import logistics_vehicle_service
from . import logistics_dispatch_batch
from . import logistics_dispatch_waybill
from . import logistics_product_unit
from . import product_template
from . import res_partner
from . import logistics_stats_service
from . import ui_label_sync
