{
    "name": "Logistics Web",
    "version": "19.0.1.0.0",
    "author": "OpenAI",
    "summary": "物流后台前端增强层",
    "license": "LGPL-3",
    "depends": [
        "web",
        "base_import",
        "logistics_dispatch",
        "logistics_trace_core",
        "logistics_trace_evidence",
        "logistics_trace_exception",
    ],
    "data": [
        "security/logistics_web_security.xml",
        "data/base_import_mapping_data.xml",
        "views/logistics_web_actions.xml",
        "views/logistics_web_menus.xml",
        "views/logistics_web_enterprise_menus.xml",
        "data/logistics_web_native_menu_cleanup.xml",
        "views/logistics_web_templates.xml",
        "views/logistics_web_batch_views.xml",
        "views/logistics_web_waybill_views.xml",
        "views/logistics_web_profile_views.xml",
        "data/logistics_web_label_sync.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "logistics_web/static/src/js/actions/logistics_action_registry.js",
            "logistics_web/static/src/js/actions/home_action.js",
            "logistics_web/static/src/js/actions/dashboard_action_v2.js",
            "logistics_web/static/src/js/actions/boss_trace_action_v2.js",
            "logistics_web/static/src/js/actions/import_center_action.js",
            "logistics_web/static/src/js/actions/import_result_action.js",
            "logistics_web/static/src/js/actions/export_result_action.js",
            "logistics_web/static/src/js/actions/driver_management_action_v2.js",
            "logistics_web/static/src/js/actions/vehicle_management_action_v2.js",
            "logistics_web/static/src/js/actions/stats_center_action.js",
            "logistics_web/static/src/js/actions/erp_document_query_action.js",
            "logistics_web/static/src/js/components/*.js",
            "logistics_web/static/src/js/services/*.js",
            "logistics_web/static/src/js/views/*.js",
            "logistics_web/static/src/js/widgets/*.js",
            "logistics_web/static/src/xml/boss_trace_templates.xml",
            "logistics_web/static/src/xml/home_action_templates.xml",
            "logistics_web/static/src/xml/dashboard_action_templates.xml",
            "logistics_web/static/src/xml/boss_trace_action_templates.xml",
            "logistics_web/static/src/xml/driver_management_templates_safe.xml",
            "logistics_web/static/src/xml/vehicle_management_templates.xml",
            "logistics_web/static/src/xml/import_center_templates.xml",
            "logistics_web/static/src/xml/import_result_templates.xml",
            "logistics_web/static/src/xml/export_result_templates.xml",
            "logistics_web/static/src/xml/stats_center_templates.xml",
            "logistics_web/static/src/xml/erp_document_query_templates.xml",
            "logistics_web/static/src/xml/list_import_button.xml",
            "logistics_web/static/src/xml/widget_templates.xml",
            "logistics_web/static/src/scss/*.scss",
        ],
    },
    "installable": True,
    "application": False,
}
