from . import selection_options
from . import hr_employee
from . import fleet_vehicle
from . import logistics_customer_profile
from . import logistics_driver_profile
from . import logistics_product_unit
from . import logistics_store_profile
from . import logistics_vehicle_profile
from . import product_template
from . import res_partner
from . import res_users
from . import stock_warehouse
