{
    "name": "WMS Task Core",
    "version": "19.0.1.0.0",
    "summary": "WMS task skeleton for receipt, putaway, outbound, picking and handover",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "stock",
        "stock_picking_batch",
        "purchase_stock",
        "erp_base",
        "logistics_base",
        "logistics_dispatch",
    ],
    "data": [
        "security/wms_task_core_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "views/stock_location_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_picking_views.xml",
        "views/purchase_order_views.xml",
        "views/logistics_dispatch_waybill_views.xml",
        "views/wms_task_views.xml",
        "views/wms_dashboard_template.xml",
    ],
    "installable": True,
    "application": False,
}
