{
    "name": "TMS Dispatch Core",
    "version": "19.0.1.0.0",
    "summary": "TMS dispatch skeleton for route, driver task, signoff and freight",
    "author": "OpenAI",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "hr",
        "fleet",
        "erp_base",
        "logistics_base",
        "logistics_dispatch",
        "logistics_trace_core",
        "wms_task_core",
    ],
    "data": [
        "security/tms_dispatch_core_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "views/logistics_profile_views.xml",
        "views/logistics_route_planning_views.xml",
        "views/logistics_dispatch_waybill_views.xml",
        "views/tms_dispatch_views.xml",
        "views/logistics_route_planning_map.xml",
    ],
    "installable": True,
    "application": False,
}
